from __future__ import annotations

import re

import markdown

DEFAULT_CSS = """
body { font-family: serif; line-height: 1.5; margin: 4%; color: black; background: white; }
h1 { font-size: 1.4em; margin-top: 0; border-bottom: 1px solid #888; padding-bottom: 0.2em; }
h2, h3 { line-height: 1.25; }
img { max-width: 100%; height: auto; }
code, pre { font-family: monospace; }
pre { background: #eee; padding: 0.5em; white-space: pre-wrap; }
.broken-link { color: #888; }
ul, ol { margin: 0.3em 0; padding-left: 1.5em; }
li { margin: 0.1em 0; }
p { margin: 0.4em 0; }
.tag { display: inline-block; background: #ddd; border: 1px solid #bbb; border-radius: 3px; padding: 1px 5px; font-size: 0.85em; margin: 0 1px; }
mark { background-color: #666; color: white; padding: 0 2px; }
.toc { margin: 1em 0; padding: 0.5em; border: 1px solid #ccc; }
.toc ul { list-style: none; padding-left: 0.8em; margin: 0.1em 0; }
.toc li { margin: 0.15em 0; }
.toctitle { font-weight: bold; display: block; margin-bottom: 0.3em; }
""".strip()

_EXTENSIONS = ["tables", "fenced_code", "attr_list", "toc", "admonition"]


def _has_h1(md: str) -> bool:
    """Check if the markdown starts with a level-1 heading."""
    for line in md.splitlines():
        s = line.strip()
        if s.startswith("# ") and not s.startswith("## "):
            return True
    return False


def _count_headings(html: str) -> int:
    """Count <h1>–<h6> elements in rendered HTML."""
    return len(re.findall(r"<h[1-6][ >]", html))


def _enrich_toc(toc_html: str, body: str) -> str:
    """Add significant list-items (with links/tags/bold) to the heading-based TOC."""
    if not toc_html:
        return toc_html

    # Find heading positions in the body
    heading_starts = [
        (m.start(), m.group(2))
        for m in re.finditer(r'<h([1-6])\s[^>]*id="([^"]*)"[^>]*>', body)
    ]
    if not heading_starts:
        return toc_html

    # For each heading section, collect significant <li> text
    section_lis: dict[str, list[str]] = {}
    for i, (start, anchor) in enumerate(heading_starts):
        if not anchor:  # skip headings without an id (shouldn't happen)
            continue
        end = heading_starts[i + 1][0] if i + 1 < len(heading_starts) else len(body)
        section = body[start:end]
        for li_m in re.finditer(r"<li>(.*?)</li>", section, re.DOTALL):
            inner = li_m.group(1)
            if re.search(r"<a\s|<span class=\"tag\"|<strong>", inner):
                text = re.sub(r"<[^>]+>", "", inner).strip()
                if text:
                    text = text[:80]
                    section_lis.setdefault(anchor, []).append(text)

    if not section_lis:
        return toc_html

    # Insert list-items into the TOC under each heading's entry
    for anchor, texts in section_lis.items():
        li_html = "".join(
            f'<li class="toc-li">· {t}</li>' for t in texts
        )
        # Insert a <ul class="toc-links"> right after the heading's anchor link.
        # Use a lambda so the replacement string isn't processed for escape sequences.
        toc_html = re.sub(
            rf'(<a href="#{re.escape(anchor)}">[^<]*</a>)',
            lambda m, _li=li_html: m.group(0) + f'<ul class="toc-links">{_li}</ul>',
            toc_html,
        )

    return toc_html


def render_markdown(md: str, css: str = DEFAULT_CSS, title: str | None = None) -> str:
    """Convert markdown to a self-contained HTML document.

    * If *title* is given and the markdown has no H1, prepend ``# {title}``.
    * If the rendered document has 3+ headings, inject a Table of Contents
      (generated by the ``toc`` extension) at the top of the body.
    """
    # Ensure every note has a visible title
    if title and not _has_h1(md):
        md = f"# {title}\n\n{md}"

    # Use the class-based API so we can access md.toc
    md_inst = markdown.Markdown(extensions=_EXTENSIONS)
    body = md_inst.convert(md)
    toc_html = getattr(md_inst, "toc", "")

    heading_count = _count_headings(body)
    try:
        toc_html = _enrich_toc(toc_html, body)
    except Exception:
        pass  # enrichment failed — use heading-only TOC
    if toc_html and heading_count >= 2:
        # Replace the auto-generated "Table of Contents" span with our own
        toc_html = toc_html.replace(
            '<span class="toctitle">Table of Contents</span>',
            '<span class="toctitle">Contents</span>',
        )
        # Inject TOC after the first H1 (title first, then TOC)
        m = re.search(r"</h1>", body)
        if m:
            body = body[: m.end()] + "\n" + toc_html + body[m.end() :]
        else:
            body = toc_html + "\n" + body

    return (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n<head>\n<meta charset="utf-8">\n'
        f"<style>\n{css}\n</style>\n</head>\n<body>\n{body}\n</body>\n</html>\n"
    )
